
  volumes:
    pg_data_production:
    static_volume:
    frontend_build_volume:

  services:
    db:
      image: postgres:13
      env_file: ./.env
      volumes:
        - pg_data_production:/var/lib/postgresql/data
      restart: unless-stopped

    backend:
      image: aamok/foodgram-backend:latest
      env_file: ./.env
      volumes:
        - static_volume:/app/collected_static

    frontend:
      image: aamok/foodgram-frontend:latest
      env_file: ./.env
      command: cp -r /app/build/. /frontend_static/
      volumes:
        - static_volume:/frontend_static

    nginx:
      image: aamok/foodgram-gateway
      volumes:
        - static_volume:/staticfiles/
      env_file: .env
      ports:
        - 8000:80
