version: '3.3'

volumes:
  pg_data:
  static:
  
services:
  db:
    image: postgres:13
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    container_name: foodgram-backend
    env_file: ../.env
    build: ../backend
    volumes:
      - ../static:/static
  frontend:
    container_name: foodgram-front
    env_file: ../.env
    build: ../frontend
    command: cp -r /app/build/. /static/
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    container_name: foodgram-proxy
    env_file: ../.env
    image: nginx:1.25.4-alpine
    ports:
      - 8000:80
    volumes:
      - ../pg_data:/var/lib/postgresql/data
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
