# Generated by Django 4.2.23 on 2025-08-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default=None, help_text='Загрузите изображение профиля.', null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
    ]
