# Generated by Django 4.2.23 on 2025-08-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Загрузите изображение профиля.', null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
    ]
